# Generated by Django 5.0.1 on 2024-01-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('asosi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('aktiv', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('jins', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=30)),
                ('yosh', models.PositiveIntegerField()),
                ('daraja', models.CharField(choices=[('Bakalavir', 'Bakalavir'), ('Magistir', 'Magistir'), ('Academik', 'Academik'), ('Fan Doctori', 'Fan Doctori')], max_length=30)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumot.fan')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumot.yonalish'),
        ),
    ]
