# Generated by Django 5.0.1 on 2024-02-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='asosi',
            field=models.BooleanField(max_length=200),
        ),
    ]
